"""
common.py

Shared machinery used by every bank-specific parser. The core idea:

  1. pdfplumber gives us every word on the page with its exact (x0, top, x1,
     bottom) bounding box -- this is the "sees the grid" superpower the
     write-up mentions. Standard PDF text extraction just gives you a wall
     of text with the column structure destroyed.

  2. We locate the header row (e.g. "Date  Narration  Chq/Ref No  ...") and
     use the x-position of each header label to define column boundaries.

  3. For every other line of text on the page, we bucket each word into the
     column whose x-range it falls into, based on x0. This reconstructs the
     table even when the PDF has NO visible ruling lines (which is the
     normal case for bank statements -- they're generated by report engines
     that position text absolutely, not by drawing an actual HTML-like
     table with borders).

  4. Rows that don't start with a valid date are treated as "continuation"
     lines (long narrations that wrap) and get appended to the previous
     row's Narration cell instead of becoming their own row.

Each bank parser (hdfc_parser.py, sbi_parser.py) just needs to supply:
  - the list of header labels to search for, in order
  - a date regex
  - the DataFrame->clean-schema step

Everything else is handled here.
"""

from __future__ import annotations
import re
from dataclasses import dataclass
from typing import Optional

import pdfplumber
import pandas as pd

DATE_RE = re.compile(r"^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}$")
AMOUNT_RE = re.compile(r"^-?[\d,]+\.\d{2}$")


@dataclass
class ColumnBounds:
    """x0/x1 boundary for one logical table column."""
    name: str
    x0: float
    x1: float

    def contains(self, word_x0: float) -> bool:
        return self.x0 <= word_x0 < self.x1


def find_header_columns(page, header_labels: list[str]) -> Optional[list[ColumnBounds]]:
    """
    Scans a page's words for a line that contains (most of) the expected
    header labels, and returns column boundaries derived from their x
    positions. Returns None if the header row isn't found on this page
    (e.g. it only appears on page 1, and this is page 7).
    """
    words = page.extract_words(use_text_flow=False, keep_blank_chars=False)
    if not words:
        return None

    # Group words by their approximate vertical position ("top"), rounded to
    # the nearest 2px, so words on the same visual line cluster together.
    lines: dict[int, list[dict]] = {}
    for w in words:
        line_key = round(w["top"] / 2) * 2
        lines.setdefault(line_key, []).append(w)

    best_line = None
    best_score = 0
    for line_words in lines.values():
        line_text = " ".join(w["text"] for w in line_words).upper()
        score = sum(1 for label in header_labels if label.upper() in line_text)
        if score > best_score:
            best_score = score
            best_line = line_words

    # Require at least half the expected headers to show up before we trust it.
    if best_line is None or best_score < max(2, len(header_labels) // 2):
        return None

    best_line = sorted(best_line, key=lambda w: w["x0"])

    # Match each header label to its word cluster, in order, then build
    # column boundaries: each column spans from its own label's x0 to the
    # next label's x0 (last column runs to page width).
    label_positions = []
    remaining = list(best_line)
    for label in header_labels:
        label_words = label.upper().split()
        match_x0 = None
        label_norm = label.upper().rstrip(".:")
        # find first remaining word (or word sequence) matching this label
        for i in range(len(remaining)):
            candidate = " ".join(w["text"] for w in remaining[i:i + len(label_words)]).upper()
            candidate = candidate.rstrip(".:")
            if candidate == label_norm or label_norm in candidate:
                match_x0 = remaining[i]["x0"]
                remaining = remaining[i + len(label_words):]
                break
        if match_x0 is not None:
            label_positions.append((label, match_x0))

    if len(label_positions) < max(2, len(header_labels) // 2):
        return None

    label_positions.sort(key=lambda t: t[1])
    bounds = []
    for i, (label, x0) in enumerate(label_positions):
        x1 = label_positions[i + 1][1] if i + 1 < len(label_positions) else page.width + 1
        bounds.append(ColumnBounds(name=label, x0=x0 - 5, x1=x1 - 5))
    return bounds


def extract_rows_by_columns(page, columns: list[ColumnBounds]) -> list[dict]:
    """
    Buckets every word on the page into its column based on x0, grouping by
    line, and returns a list of {column_name: cell_text} dicts -- one per
    visual line on the page (including narration continuation lines, which
    the caller is responsible for merging upward).
    """
    words = page.extract_words(use_text_flow=False, keep_blank_chars=False)
    lines: dict[int, list[dict]] = {}
    for w in words:
        line_key = round(w["top"] / 2) * 2
        lines.setdefault(line_key, []).append(w)

    rows = []
    for top in sorted(lines.keys()):
        line_words = sorted(lines[top], key=lambda w: w["x0"])
        row = {col.name: "" for col in columns}
        for w in line_words:
            for col in columns:
                if col.contains(w["x0"]):
                    row[col.name] = (row[col.name] + " " + w["text"]).strip()
                    break
        # Skip fully blank rows
        if any(v for v in row.values()):
            rows.append(row)
    return rows


def clean_amount(value: str) -> Optional[float]:
    """'1,23,456.78' -> 123456.78 (handles Indian lakh-style commas). '' -> None."""
    if not value:
        return None
    value = value.strip().replace(",", "")
    if not re.match(r"^-?\d+\.\d{2}$", value):
        return None
    return float(value)


def clean_date(value: str, dayfirst: bool = True) -> Optional[str]:
    """Normalises DD/MM/YY, DD-MM-YYYY etc to ISO YYYY-MM-DD string."""
    if not value or not DATE_RE.match(value.strip()):
        return None
    try:
        ts = pd.to_datetime(value.strip(), dayfirst=dayfirst, errors="coerce")
        if pd.isna(ts):
            return None
        return ts.strftime("%Y-%m-%d")
    except Exception:
        return None


def merge_continuation_rows(raw_rows: list[dict], date_column: str, narration_column: str) -> list[dict]:
    """
    Bank statements wrap long narrations onto extra lines with no date /
    amounts of their own. This walks the raw per-line rows and folds any
    line that doesn't start with a valid date into the previous real row's
    narration field instead of treating it as a new transaction.
    """
    merged: list[dict] = []
    for row in raw_rows:
        starts_new_txn = bool(DATE_RE.match(row.get(date_column, "").strip()))
        if starts_new_txn or not merged:
            merged.append(dict(row))
        else:
            # continuation line -- glue every non-empty cell onto narration
            extra = " ".join(v for k, v in row.items() if v).strip()
            if extra:
                merged[-1][narration_column] = (merged[-1].get(narration_column, "") + " " + extra).strip()
    return merged


def dataframe_to_outputs(df: pd.DataFrame, out_base_path: str) -> dict:
    """Writes the cleaned DataFrame to .xlsx and .csv, returns both paths."""
    xlsx_path = f"{out_base_path}.xlsx"
    csv_path = f"{out_base_path}.csv"
    df.to_excel(xlsx_path, index=False)
    df.to_csv(csv_path, index=False)
    return {"xlsx": xlsx_path, "csv": csv_path}
